# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder

# Enable Corepack to use pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy manifest files
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Copy source
COPY src ./src

# Install deps and build
RUN pnpm install --frozen-lockfile && pnpm run build

# Runner stage
FROM node:lts-alpine AS runner

# Enable Corepack and pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# Copy build artifacts and manifest
COPY --from=builder /app/dist ./dist
COPY package.json pnpm-lock.yaml ./

# Install only production dependencies
RUN pnpm install --prod --frozen-lockfile

# Start server via STDIO
ENTRYPOINT ["node", "dist/index.js"]
