# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY package.json pnpm-lock.yaml tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and production dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

ENTRYPOINT ["node", "dist/index.js"]
