# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# --- Builder Stage ---
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json pnpm-lock.yaml* ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# --- Runner Stage ---
FROM node:lts-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Default command: runs the MCP server
CMD ["node", "dist/index.js"]
